name: Laravel

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd public_html/sppd
            if [ ! -d ".git" ]; then
              git init -b production
              git remote add origin https://github.com/Hikuroshi/sppd_laravel_10
            fi
            rm -f .git/index.lock
            git fetch origin production
            git reset --hard origin/production
            git clean -f -d
            php composer.phar install --ignore-platform-reqs
            chmod -R 777 storage bootstrap/cache
            php -r "file_exists('.env') || copy('.env.example', '.env');"
            php artisan key:generate
            sed -i "s/DB_DATABASE=.*/DB_DATABASE=${{ secrets.DB_DATABASE }}/g" .env
            sed -i "s/DB_USERNAME=.*/DB_USERNAME=${{ secrets.DB_USERNAME }}/g" .env
            sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/g" .env
            php artisan optimize:clear
