name: Laravel

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Install Dependencies
      #   run: composer update --ignore-platform-reqs
      # - name: Directory Permissions
      #   run: chmod -R 777 storage bootstrap/cache
      # - name: Copy .env
      #   run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      # - name: Generate key
      #   run: php artisan key:generate

      # - name: Update .env for Database
      #   run: |
      #     echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
      #     echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
      #     echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd public_html/sppd
            git fetch origin production
            git reset --hard origin/production
            composer update --ignore-platform-reqs
            chmod -R 777 storage bootstrap/cache
            php -r "file_exists('.env') || copy('.env.example', '.env');"
            php artisan key:generate
            sed -i "s/DB_DATABASE=.*/DB_DATABASE=${{ secrets.DB_DATABASE }}/g" .env
            sed -i "s/DB_USERNAME=.*/DB_USERNAME=${{ secrets.DB_USERNAME }}/g" .env
            sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/g" .env
            php artisan optimize:clear
            php artisan migrate:fresh --seed
